---
- name: roles/snmp/tasks/snmp.yml
  assert: { that: true, quiet: true }

- name: Install snmp related packages
  dnf:
    name: 
      - net-snmp
      - net-snmp-utils
      - net-snmp-devel
  become: yes

- name: apply snmpd.conf template
  template:
    src: snmpd.conf
    dest: /etc/snmp/
  become: yes
  notify: restart snmpd 

- name: Make sure snmpd is running
  systemd:
    name: snmpd
    state: started
    enabled: yes
  become: yes

- name: apply snmptrapd.conf template
  template:
    src: snmptrapd.conf
    dest: /etc/snmp/
  become: yes

- name: Make sure snmptrapd is running
  systemd:
    name: snmptrapd
    state: restarted
    enabled: yes
  become: yes

- name: Grant Access to snmpd
  firewalld:
    zone: public
    permanent: yes
    rich_rule: 'rule family=ipv4 source address={{ SNMP_MANAGER_CIDR }} service name={{ item }} accept'
    state: enabled
  become: yes
  notify: reload firewalld
  loop:
    - snmp
    - snmptrap
