---
- name: roles/httpd/tasks/main.yml
  assert: { that: true, quiet: true }

- name: Install httpd
  dnf:
    name: httpd
  become: true

- name: Deploy httpd.conf for portno modification
  template:
    src: httpd.conf
    dest: /etc/httpd/conf/
  become: true

- name: Start httpd
  systemd:
    name: httpd
    state: started
  become: true

- name: Open firewall(httpd service)
  ansible.posix.firewalld:
    service: http
    permanent: true
    immediate: true
    offline: true
    state: enabled
  become: True
  ignore_errors: true
  when: HTTPD_PORT == 80

- name: Open firewall
  ansible.posix.firewalld:
    port: "{{ HTTPD_PORT }}/tcp"
    permanent: true
    immediate: true
    offline: true
    state: enabled
  become: True
  loop:
    - "{{ HTTPD_PORT }}"
    - https
  ignore_errors: true
  when: HTTPD_PORT != 80
