# Basic Congiguration Control
---
- name: roles/base/tasks/main.yml
  assert: { that: true, quiet: true }

- import_tasks: powertools.yml
  tags: pt

- import_tasks: mandatory.yml
- import_tasks: time.yml
- import_tasks: prompt.yml
- import_tasks: selinux.yml
- import_tasks: joe.yml
- import_tasks: guest_addition.yml
- import_tasks: sshd.yml

- name: Run and enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes
  become: yes
