---
- name: roles/base/tasks/selinux.yml
  assert: { that: true, quiet: true }

- name: Install tools required for disabling selinux
  dnf: 
    name: python3-libselinux
    state: present
  become: yes

- name: Disable selinux 
  selinux:
    state: disabled
  become: yes
