---
- name: roles/base/tasks/sshd.yml
  assert: { that: true, quiet: true }

- name: Disable reverse dns lookup
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: ^GSSAPIAuthentication
    line: GSSAPIAuthentication no
  become: yes
